name: sweyer
description: Open source music player built with Flutter
homepage: https://github.com/nt4f04uNd/sweyer
repository: https://github.com/nt4f04uNd/sweyer
issue_tracker: https://github.com/nt4f04uNd/sweyer/issues
publish_to: none
version: 1.0.9+11

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  uuid: ^3.0.4
  path: ^1.8.0
  async: ^2.5.0
  rxdart: ^0.26.0
  sliver_tools: ^0.2.1
  animations: ^2.0.2
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  percent_indicator: ^4.2.2
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  firebase_analytics: ^10.2.0
  cloud_functions: ^4.1.0
  package_info_plus: ^3.1.0
  url_launcher: ^6.0.3
  lottie: ^2.3.2
  auto_size_text: ^3.0.0
  marquee: ^2.1.0
  equatable: ^2.0.0
  device_info_plus: ^8.2.0
  enum_to_string: ^2.0.1
  sqflite: ^2.0.0+3
  boxy: ^2.0.0
  back_button_interceptor: ^6.0.0
  flutter_sticky_header: ^0.6.0
  palette_generator: ^0.3.3+2
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.1.1
  clock: ^1.1.0
  styled_text: ^7.0.0
  android_content_provider: ^0.3.0
  collection: ^1.16.0
  theme_tailor_annotation: ^2.0.0
  riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  memoize: ^3.0.0
  tuple: ^2.0.1

  # quick_actions: ^0.6.0 # TODO: quick actions are blocked on https://github.com/ryanheise/audio_service/issues/671

  # fluttertoast: ^8.0.3
  fluttertoast:
    # path: C:/dev/projects/native/FlutterToast

    # Using this branch for changing font family
    git: 
      url: https://github.com/nt4f04uNd/fluttertoast/
      ref: f753a91591569acece70a9e8748745efa9faabfb # patch
  just_audio: ^0.9.18
  
    # path: C:/dev/projects/native/just_audio/just_audio
  
    # git: 
    #   url: C:/dev/projects/native/just_audio
    #   ref: master
    #   path: just_audio
  audio_service:
    # Using this branch for custom notifications https://github.com/nt4f04uNd/audio_service/commits/sweyer
    # See https://github.com/ryanheise/audio_service/issues/633

    # path: C:/dev/projects/native/audio_service/audio_service
    # path: /Users/nt4f04und/dev/prj/audio_service/audio_service

    git: 
      url: https://github.com/nt4f04uNd/audio_service
      ref: sweyer
      path: audio_service
  nt4f04unds_widgets:
    # path: c:/dev/projects/native/nt4f04unds_widgets/
    # path: /Users/nt4f04und/dev/prj/nt4f04unds_widgets

    git:
      url: https://github.com/nt4f04uNd/nt4f04unds_widgets/
      ref: 3.0.0

  sweyer_plugin:
    path: sweyer_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.15.0
  theme_tailor: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  generate: true
  uses-material-design: true

  assets:
   - assets/
   - assets/images/
    # don't include a whole folder here because of README
   - assets/animations/play_pause.json
   - assets/animations/checkmark.json

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/manrope-extrabold.ttf
          weight: 800
        - asset: assets/fonts/Manrope/manrope-bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/manrope-semibold.ttf
          weight: 600
    - family:  SweyerIcons
      fonts:
       - asset: assets/fonts/SweyerIcons/SweyerIcons.ttf
